import { type Manifest } from "@forsakringskassan/docs-generator";

/**
 * Fetch document pages and examples for documentation generated by
 * `@forsakringskassan/docs-generator`.
 *
 * @public
 * @since %version%
 * @param on - Cypress `on` callback from `setupNodeEvents`.
 * @param config - Cypress `config` parameter from `setupNodeEvents`.
 * @param docs - A `Generator` instance.
 * @param sourceFiles - A set of source files generate manifest for.
 * @returns A promise resolved with the updated cypress configuration.
 */
export async function docsGeneratorPlugin<T extends unknown[]>(
    _on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions,
    docs: { manifest(sourceFiles: T): Promise<unknown> },
    sourceFiles: T,
): Promise<Cypress.PluginConfigOptions> {
    const manifest = (await docs.manifest(sourceFiles)) as Manifest;
    const pages = manifest.pages.filter((it) => {
        return it.path.endsWith(".html");
    });
    config.expose["pages"] = pages;
    return config;
}
